# Stage 1 - build the api server
FROM node:16-alpine

WORKDIR /usr/src/app

RUN wget -qO- https://get.pnpm.io/install.sh | sh -

COPY package.json pnpm-lock.yaml ./
COPY prisma ./prisma

RUN pnpm install

COPY . .

EXPOSE 4000
CMD [ "pnpm", "run", "dev" ]
