# Stage 1 - build the api server
FROM node:14-alpine

WORKDIR /usr/src/app

RUN wget -qO- https://get.pnpm.io/v6.16.js | node - add --global pnpm

COPY package.json pnpm-lock.yaml ./
COPY prisma ./prisma

RUN pnpm install

COPY . .

ENV NODE_ENV production

EXPOSE 4000
CMD [ "npm", "run", "dev" ]
