name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          # cache: "npm"

      - run: npm ci

      - name: Test
        run: npx tsc --noEmit

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag stxstats-api:$(date +%s)

  test-client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          # cache: "npm"

      - run: npm ci

      - name: Test
        run: npx next lint
