name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api

    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: 7.1

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Generate prisma client
        run: pnpm prisma generate

      - name: Test
        run: pnpm tsc --noEmit

  test-api-docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          driver: docker

      # Same process as for the release, this step ensure that the docker release is not broken
      - name: Build the Docker image
        uses: docker/build-push-action@v2
        with:
          push: false
          context: .
          file: ./api/Dockerfile
          tags: stxstats-api:test-api-docker

      # Print docker images so we can check the size
      - name: Print docker image size
        run: docker images | grep stxstats-api

  test-client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client

    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: 7.1

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Test
        run: pnpm next lint
