name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api

    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.6

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Test
        run: pnpx tsc --noEmit

      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile --tag stxstats-api:$(date +%s)
          # Print docker images so we can check the size
          docker images | grep stxstats-api

  test-client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client

    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.23.6

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Test
        run: pnpx next lint
